"""initial schema

Revision ID: f4b062c1c619
Revises: 
Create Date: 2026-06-28 18:23:50.508603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b062c1c619'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('central_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('central_question_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('central_question_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['central_question_id'], ['central_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initiatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phase', sa.Enum('verkenning', 'experiment', 'pilot', 'opschaling', name='initiative_phase'), nullable=False),
    sa.Column('status', sa.Enum('actief', 'gestopt', 'afgerond', name='initiative_status'), nullable=False),
    sa.Column('horizon', sa.Enum('h1', 'h2', 'h3', name='horizon'), nullable=True),
    sa.Column('mds', sa.Text(), nullable=True),
    sa.Column('mds_id', sa.String(length=36), nullable=True),
    sa.Column('central_question', sa.Text(), nullable=True),
    sa.Column('trekker', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('type_ai_gebruik', sa.Enum('bouwen_met_ai', 'ai_in_bouwsels', 'ai_in_bestaande_tools', 'persoonlijke_productiviteit', 'mix', name='type_ai_gebruik'), nullable=True),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mds_id'], ['mds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_tags',
    sa.Column('central_question_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['central_question_id'], ['central_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('central_question_id', 'tag_id')
    )
    op.create_table('curation_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('curation_id', sa.String(length=36), nullable=False),
    sa.Column('initiative_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['curation_id'], ['curations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossier_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('initiative_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossier_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('initiative_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hypotheses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('initiative_id', sa.String(length=36), nullable=False),
    sa.Column('parent_hypothesis_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('value', 'growth', 'compliance', name='hypothesis_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'bevestigd', 'weerlegd', 'vervallen', name='hypothesis_status'), nullable=False),
    sa.Column('learning', sa.Text(), nullable=True),
    sa.Column('commentary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initiative_questions',
    sa.Column('initiative_id', sa.String(length=36), nullable=False),
    sa.Column('central_question_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['central_question_id'], ['central_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('initiative_id', 'central_question_id')
    )
    op.create_table('initiative_tags',
    sa.Column('initiative_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('initiative_id', 'tag_id')
    )
    op.create_table('one_pagers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('initiative_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('audience', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('one_pagers')
    op.drop_table('initiative_tags')
    op.drop_table('initiative_questions')
    op.drop_table('hypotheses')
    op.drop_table('dossier_notes')
    op.drop_table('dossier_files')
    op.drop_table('curation_items')
    op.drop_table('question_tags')
    op.drop_table('initiatives')
    op.drop_table('central_question_files')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('mds')
    op.drop_table('curations')
    op.drop_table('central_questions')
    # ### end Alembic commands ###
